export const sampleModels = [
  {
    id: 'model-1',
    owner: 'user1',
    name: 'GPT-4 Fine-tuned',
    description: 'A fine-tuned version of GPT-4 for general tasks.',
    avatar: '/placeholder-model.png',
    isPrivate: false,
    likes: 1200,
    downloads: 2500,
    updatedAt: '2 days ago',
  },
  {
    id: 'model-2',
    owner: 'user2',
    name: 'Stable Diffusion v2',
    description: 'Latest version of the popular image generation model.',
    avatar: '/placeholder-model.png',
    isPrivate: false,
    likes: 850,
    downloads: 1800,
    updatedAt: '5 days ago',
  },
  {
    id: 'model-3',
    owner: 'user1',
    name: 'BERT Sentiment Analysis',
    description: 'A BERT model fine-tuned for sentiment analysis.',
    avatar: '/placeholder-model.png',
    isPrivate: true,
    likes: 320,
    downloads: 500,
    updatedAt: '1 week ago',
  },
  {
    id: 'model-4',
    owner: 'user3',
    name: 'Whisper ASR',
    description: 'Automatic speech recognition model.',
    avatar: '/placeholder-model.png',
    isPrivate: false,
    likes: 550,
    downloads: 900,
    updatedAt: '3 weeks ago',
  },
];

export const sampleDatasets = [
  {
    id: 'dataset-1',
    owner: 'user1',
    name: 'Common Voice',
    description: 'A multi-language dataset of voices.',
    avatar: '/placeholder-dataset.png',
    isPrivate: false,
    likes: 750,
    downloads: 1500,
    updatedAt: '1 week ago',
    numRows: 120000,
  },
  {
    id: 'dataset-2',
    owner: 'user2',
    name: 'ImageNet Subset',
    description: 'A smaller version of the ImageNet dataset.',
    avatar: '/placeholder-dataset.png',
    isPrivate: false,
    likes: 420,
    downloads: 800,
    updatedAt: '2 weeks ago',
    numRows: 50000,
  },
  {
    id: 'dataset-3',
    owner: 'user3',
    name: 'BookCorpus',
    description: 'A dataset of books for language modeling.',
    avatar: '/placeholder-dataset.png',
    isPrivate: true,
    likes: 210,
    downloads: 300,
    updatedAt: '4 weeks ago',
    numRows: 80000,
  },
  {
    id: 'dataset-4',
    owner: 'user1',
    name: 'Sentiment140',
    description: 'A dataset for sentiment analysis with tweets.',
    avatar: '/placeholder-dataset.png',
    isPrivate: false,
    likes: 380,
    downloads: 600,
    updatedAt: '6 weeks ago',
    numRows: 140000,
  },
];